# Generated by Django 5.2.16 on 2026-07-26 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='título')),
                ('note', models.TextField(blank=True, verbose_name='anotação')),
                ('happened_on', models.DateField(verbose_name='aconteceu em')),
                # o upload_to virava uma função do models.py, que não existe mais;
                # a migração 0002 move essas fotos pra dentro do banco.
                ('image', models.ImageField(upload_to='memorias/', verbose_name='foto')),
                ('location', models.CharField(blank=True, max_length=140, verbose_name='lugar')),
                ('author', models.CharField(choices=[('ele', 'Ele'), ('ela', 'Ela'), ('nos', 'Nós dois')], default='nos', max_length=8, verbose_name='quem guardou')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='momento favorito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'memória',
                'verbose_name_plural': 'memórias',
                'ordering': ['happened_on', 'created_at'],
                'indexes': [models.Index(fields=['happened_on'], name='memories_me_happene_413771_idx')],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(choices=[('ele', 'Ele'), ('ela', 'Ela'), ('nos', 'Nós dois')], default='nos', max_length=8, verbose_name='quem escreveu')),
                ('text', models.TextField(verbose_name='recado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='memories.memory')),
            ],
            options={
                'verbose_name': 'anotação',
                'verbose_name_plural': 'anotações',
                'ordering': ['created_at'],
            },
        ),
    ]
