# Generated by Django 5.2.17 on 2026-10-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_fotos_no_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='unlock_date',
            field=models.DateTimeField(blank=True, help_text='Se definido, a memória só poderá ser vista após esta data.', null=True),
        ),
    ]
