# Generated by Django 5.2.17 on 2026-10-03 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_memory_unlock_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='memories/gallery/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='memories.memory')),
            ],
        ),
    ]
