# Generated by Django 5.2.17 on 2026-10-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_memoryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoryimage',
            name='image',
        ),
        migrations.AddField(
            model_name='memoryimage',
            name='image_data',
            field=models.BinaryField(default=b'', verbose_name='foto (bytes)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoryimage',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='memoryimage',
            name='image_mime',
            field=models.CharField(default='image/webp', max_length=40),
        ),
        migrations.AddField(
            model_name='memoryimage',
            name='thumb_data',
            field=models.BinaryField(default=b'', verbose_name='miniatura (bytes)'),
            preserve_default=False,
        ),
    ]
