# Generated by Django 5.2.17 on 2026-10-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0005_remove_memoryimage_image_memoryimage_image_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='notificação enviada'),
        ),
    ]
